BSP = stm32f10x
# check by st-info --probe
# stm32f10x_ld stm32f10x_ld_vl stm32f10x_md stm32f10x_md_vl stm32f10x_hd stm32f10x_hd_vl stm32f10x_xl stm32f10x_cl
SOC = stm32f10x_md
BOARD = stm32_min_dev

SOURCES += $(CURDIR)/main.c \
	   $(CURDIR)/mpu6050.c \
	   $(CURDIR)/servo_pwm.c
