#
# Copyright (C) <2018>  Bin Yang <byang1217@gmail.com>
#

CFLAGS += -I$(CURDIR)
SOURCES += $(CURDIR)/print.c \
	   $(CURDIR)/prf.c \
	   $(CURDIR)/sprintf.c \
	   $(CURDIR)/shell.c \
	   $(CURDIR)/string.c
