#
# Copyright (C) <2018>  Bin Yang <byang1217@gmail.com>
#

CFLAGS += -I$(CURDIR)/Virtual_COM_Port/inc
SOURCES += $(CURDIR)/Virtual_COM_Port/src/hw_config.c
SOURCES += $(CURDIR)/Virtual_COM_Port/src/stm32_it.c
SOURCES += $(CURDIR)/Virtual_COM_Port/src/usb_desc.c
SOURCES += $(CURDIR)/Virtual_COM_Port/src/usb_endp.c
SOURCES += $(CURDIR)/Virtual_COM_Port/src/usb_istr.c
SOURCES += $(CURDIR)/Virtual_COM_Port/src/usb_prop.c
SOURCES += $(CURDIR)/Virtual_COM_Port/src/usb_pwr.c
#SOURCES += $(CURDIR)/Virtual_COM_Port/src/virtualComPort.c
