#
# Copyright (C) <2018>  Bin Yang <byang1217@gmail.com>
#

CFLAGS += -I$(CURDIR)/BatReader
SOURCES += $(CURDIR)/BatReader/BatReader.cpp

CFLAGS += -I$(CURDIR)/MaxMatrix
SOURCES += $(CURDIR)/MaxMatrix/MaxMatrix.cpp

CFLAGS += -I$(CURDIR)/Oscillator
SOURCES += $(CURDIR)/Oscillator/Oscillator.cpp

CFLAGS += -I$(CURDIR)/TimerFreeTone
SOURCES += $(CURDIR)/TimerFreeTone/TimerFreeTone.cpp

CFLAGS += -I$(CURDIR)/OttoARM
SOURCES += $(CURDIR)/OttoARM/OttoARM.cpp
